spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
          frequencyPenalty: 1.6
          maxCompletionTokens: 150
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  liquibase:
    enabled: false
  profiles:
    default: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db
    username: sa
    password: sa
  h2:
    console.enabled: true
  jpa:
    open-in-view: true

logging:
  level:
    root: DEBUG
  file:
    path: ./logs

---
spring:
  config:
    import: optional:configtree:/run/secrets/
    activate:
      on-profile: prod
  datasource:
    driverClassName: org.postgresql.Driver
    url: { db.url }
    username: { db.username }
    password: { db.password }
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
